//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LivevoxAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LivevoxAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to { 
        ///  &quot;termCodeCategories&quot;: [ 
        ///    { 
        ///      &quot;termCodes&quot;: [ 
        ///        { 
        ///          &quot;id&quot;:&quot;2859344&quot;, 
        ///          &quot;name&quot;:&quot;BANKRUPTCY&quot;, 
        ///          &quot;lvResultId&quot;:&quot;724&quot;, 
        ///          &quot;lvResult&quot;:&quot;AGENT - Bankrupt&quot;, 
        ///          &quot;reportDisplayOrder&quot;:0, 
        ///          &quot;previewDialEnabled&quot;:false, 
        ///          &quot;actionType&quot;:&quot;RPC_WITHOUT_PAYMENT&quot;, 
        ///          &quot;paymentAmtRequired&quot;:false, 
        ///          &quot;triggerDnc&quot;:true 
        ///        }, 
        ///        { 
        ///          &quot;id&quot;:&quot;2859386&quot;, 
        ///          &quot;name&quot;:&quot;ELECTRONIC PAYMENT&quot;, 
        ///          &quot;lv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetDispositionsResult {
            get {
                return ResourceManager.GetString("GetDispositionsResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///   &quot;services&quot;:    [
        ///      {
        ///         &quot;serviceId&quot;: 46014,
        ///         &quot;serviceName&quot;: &quot;Omega_Manual_RT&quot;
        ///      },     
        ///            {
        ///         &quot;serviceId&quot;: 22131,
        ///         &quot;serviceName&quot;: &quot;AgentReg (Agent Call Out 7)&quot;
        ///      }
        ///   ],
        ///   &quot;homeAgent&quot;: true,
        ///   &quot;phoneNumber&quot;: &quot;6503517524&quot;
        ///}.
        /// </summary>
        internal static string GetListOfServicesResult {
            get {
                return ResourceManager.GetString("GetListOfServicesResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;screenPopRow&quot;: [{
        ///        &quot;key&quot;: &quot;FIRST NAME&quot;,
        ///        &quot;value&quot;: &quot;LV&quot;
        ///    },
        ///    {
        ///        &quot;key&quot;: &quot;LAST NAME&quot;,
        ///        &quot;value&quot;: &quot;SUP&quot;
        ///    },
        ///    {
        ///        &quot;key&quot;: &quot;ACCOUNT NUMBER&quot;,
        ///        &quot;value&quot;: &quot;abc&quot;
        ///    },
        ///    {
        ///        &quot;key&quot;: &quot;PHONE DIALED&quot;,
        ///        &quot;value&quot;: &quot;9174645253&quot;
        ///    },  
        ///    {
        ///        &quot;key&quot;: &quot;Call Direction&quot;,
        ///        &quot;value&quot;: &quot;Outbound&quot;
        ///    },
        ///    {
        ///        &quot;key&quot;: &quot;Classification&quot;,
        ///        &quot;value&quot;: &quot;Spanish&quot;
        ///    },  
        ///    {
        ///        &quot;key&quot;: &quot;Call Skill Name&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetScreenPopResults {
            get {
                return ResourceManager.GetString("GetScreenPopResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;features&quot;: {
        ///        &quot;notReadyReasonCodes&quot;: null,
        ///        &quot;agentNotesEnabled&quot;=&quot;true&quot;,
        ///        &quot;agentToAgentTransferEnabled&quot;: true,
        ///        &quot;callRecordingControlEnabled&quot;: true,
        ///        &quot;reasonCodesEnabled&quot;: false,
        ///        &quot;featureCode&quot;: 2,
        ///        &quot;manualOptionEnabled&quot;: true,
        ///        &quot;manualPreview&quot;: null,
        ///        &quot;manualPreviewButtonEnabled&quot;: false,
        ///        &quot;manualTransferEnabled&quot;: true,
        ///        &quot;phoneBookTransferEnabled&quot;: true,
        ///        &quot;confirmOnPreviewDial&quot;: false,
        ///        &quot;previewDefaul [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetServiceDetailsResult {
            get {
                return ResourceManager.GetString("GetServiceDetailsResult", resourceCulture);
            }
        }
    }
}
